name: Run Tests

on: [push, pull_request]

jobs:
  test:
    name: Test on multiple OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

   
    - name: Run tests
      run: python -m unittest discover

    - name: Upload test results (only if on Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./test-results
